# Generated by Django 5.2.6 on 2025-09-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.IntegerField(),
        ),
    ]
